### ISSUE TITLE
MainPanel and NavigationDrawer overlapped

### ISSUE THREAD

**Issue by daothanhduy305** [daothanhduy305/MusicHub#2]
The 2 views are still overlapped, more specifically, the main panel overlaps on the navigation drawer when the window's width is being narrowed

**Comment by daothanhduy305** [comment]
More info: it wouldn't happen on start up, until the user switch back to AllSongsView from another view

**Comment by daothanhduy305** [comment]
More info: happens specifically when returning from viewing an album

**Comment by hoangng1996** [comment]
Already fixed!
